### ISSUE TITLE
Meeting Markers not displaying when lang_enum="en"

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-meeting-map#18]
When lang_enum="en" it doesn't show all of the meeting markers. Specifically, I was using Racine, WI and pulling from https://meetings.namilwaukee.org/main_server. If I remove lang_enum="en" I see all of the meeting markers for the whole region. If I include lang_enum="en" in the shortcode I only see meeting markers around the city of Milwaukee (for the whole region).

**Comment by otrok7** [comment]
fixed in 1.0.4

**Comment by otrok7** [comment]
Also, you can now specify the language on the settings page, so you don't need lang_enum in the shortcode
