### ISSUE TITLE
google region bias

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-meeting-map#8]
in some tests I did region bias does not seem to be working well, maybe component biasing would be better.

**Comment by pjaudiomv** [comment]
https://developers.google.com/maps/documentation/geocoding/intro

https://developers.google.com/maps/documentation/javascript/examples/geocoding-component-restriction

**Comment by otrok7** [comment]
Component doesn't really fit...German region is Germany and Austria.  And some places may want states and not countries, and it starts being hard for the user.  I think having an optional bounding box is the most general solution.  Does that resolve the issue?

**Comment by pjaudiomv** [comment]
that sounds fine to me, or add ability to optionally add a component filter. either way is fine.
